expose:
  type: ingress
  tls:
    enabled: true
    secretName: "harbor-secret"
  ingress:
    hosts:
      core: registry.jaychang.cn
      notary: notary.jaychang.cn
    annotations:
      kubernetes.io/ingress.class: "nginx"
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/proxy-body-size: "0"

externalURL: https://registry.jaychang.cn

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      existingClaim: "harbor-registry-pvc"
    chartmuseum:
      existingClaim: "harbor-chartmuseum-pvc"
    jobservice:
      existingClaim: "harbor-jobservice-pvc"
    database:
      existingClaim: "harbor-database-pvc"
    redis:
      existingClaim: "harbor-redis-pvc"
